# -*- coding: utf-8 -*-
"""stop_words.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/yaswanthraju1098/Data-handling-/blob/main/stop_words.ipynb
"""

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

def remove_stop_words(string):
  stop_words = set(stopwords.words('english'))
  words = string.split()
  filteredwords = [word for word in words if word.lower()not in stop_words]
  new_string=''.join(filteredwords)
  return new_string

input="a about above actually after again against all almost also although always am an and any are as at"
result=remove_stop_words(input)
print("modified string:",result)

input_string="This is an example sentence to remove stop words from"
result=remove_stop_words(input_string)
print("original string:",input_string)
print("modified string:",result)

!pip install nltk

import nltk
nltk.download('punkt')

import matplotlib.pyplot as plt
from collections import Counter
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def count_stopwords(text):
    stop_words = set(stopwords.words('english'))
    words = word_tokenize(text.lower())
    word_count = Counter(words)
    stopwords_count = {word: count for word, count in word_count.items() if word in stop_words}
    return stopwords_count

def remove_stop_words(text):
  stop_words=set(stopwords.words('english'))
  words=text.split()
  filtered_words=[word for word in words if word.lower() not in stop_words]
  new_string=''.join(filtered_words)
  return new_string

def plot_bar_chart(data):
    words = list(data.keys())
    counts = list(data.values())
    plt.bar(words, counts)
    plt.xlabel('Stopwords')
    plt.ylabel('Count')
    plt.title('Stopwords Count')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    text = ("Stop words are a set of commonly used words in a language")
    remove_stop_words(text)
    stopwords_count = count_stopwords(text)
    print("Stopwords count:", stopwords_count)
    plot_bar_chart(stopwords_count)

